#!/bin/bash

dir='/usr/lib/apkkey'
napk="$@"

function android_pull_apk()
{
	if [ -z "$1" ]; then
		echo "Anda harus lulus paket untuk fungsi ini"
		echo "Ex: android_pull_apk \"com.android.contacts\""
		return 1
	fi
	if [ -z "$(adb shell pm list packages | grep $1)" ]; then
		echo "invalid packet list!"
		return 1
	fi
	apk_path="`adb shell pm path $1 | sed -e 's/package://g' | tr '\n' ' ' | tr -d '[:space:]'`"
	apk_name="`basename ${apk_path} | tr '\n' ' ' | tr -d '[:space:]'`"
	destination="$HOME/project/android/apk"
	adb pull ${apk_path} ${destination}
	echo -e "\nAPK simpan di \"$destination/$apk_name\""
}
function data_apk(){
	if [ -z "$1" ]; then
		echo "Anda harus lulus paket untuk fungsi ini"
		echo "Ex: android_pull_apk \"com.android.contacts\""
		return 1
	fi
	if [ -z "$(adb shell pm list packages | grep $1)" ]; then
		echo "invalid packet list!"
		return 1
	fi
	apk_path="`adb shell pm path $1 | sed -e 's/package://g' | tr '\n' ' ' | tr -d '[:space:]'`"
	apk_name="`basename ${apk_path} | tr '\n' ' ' | tr -d '[:space:]'`"
	destination="/root/project/android/backup/"

	read -p "backup atau kembalikan data? b/k : " rest
	if [ "$rest" = "b" ]; then
		cd $destination
        	adb backup -f $paket".ab" $paket
        	echo -e "\ndata APK tersimpan "
	fi
	if [ "$rest" = "k" ]; then
		read -p "Yakin mau KEMBALIKAN? : " alert
		if [ "$alert" = "y" ]; then
			ls -l $destination
			read -p "Masukan ab file: " abf
			adb restore $destination$abf
		fi
	fi
}

function apk_to_class() {
	read -p "-->> Nama apk -> oke pesawat.apk  : " dnapk
	control=`ls /root/hack/smali | grep "$dnapk"`

	if [ "$control" = "$dnapk" ]; then
		read -p "-- file sudah ada ganti? y/t : " g
		if [ "$g" = "y" ]; then
			rm -R /root/hack/smali/$dnapk
			apkkey decompile
		fi
	else
		mkdir /root/hack/smali/"$dnapk"
		cp "$dnapk" /root/hack/smali/"$dnapk"
		cd /root/hack/smali/"$dnapk"
		apktool d "$dnapk"
		mkdir java
		mv "$dnapk" java
		cd java
		dex2jar "$dnapk"
		find_jar=`ls | grep *.jar`
		a=`unzip $find_jar`
		at=($(echo "$a" | tr ':' '\n'))

		read -p "java semua class? y/t: " jcontrol
		for i in "${!at[@]}"; do
			if [ $jcontrol = "y" ]; then
				if [ ${at[i]} = "inflating" ]; then
					jsplit=($(echo "${at[i+1]}" | tr '.' '\n'))
					echo "$jsplit".java
					vclass "${at[i+1]}" > $jsplit".java"
					rm "${at[i+1]}"
				elif [ ${at[i]} = "creating" ]; then
					folder="${at[i+1]}"
					echo ""
					echo "------>>>> proses di folder: $folder"
				fi
			fi
		done

	fi
}

if [ "$napk" = "" ]; then
	echo "key       : Masukan nama apk contoh --> apkkey pesawat.apk"
	echo "backup    : pastikan usb tersambung > contoh --> apkkey backup"
	echo "decompile : Masukan nama apk dan otomatis tersimpan di /root/hack/smali/nama_apk --> apkkey decompile"
	echo "compile   : ada wizard, pastikan ada di folder yang ada file apktool.yml"
elif [ "$napk" = "decompile" ]; then
	apk_to_class
elif [ "$napk" = "compile" ]; then
	apktool b
	cd dist
	rm out.apk
	ncapk=`ls | grep "apk"`
	java -jar $dir/signapk.jar $dir/testkey.x509.pem $dir/testkey.pk8 $ncapk "out.apk"
	ls
fi
if [ "$napk" = "backup" ]; then
	adb shell pm list packages
	read -p "-->> Masukan backup package: " paket
	read -p "-->> Pilih data atau apk? d/a: " pil

	if [ "$pil" = "d" ]; then
		data_apk $paket
	fi
	if [ "$pil" = "a" ]; then
		android_pull_apk $paket
	fi
fi
