#!/bin/bash

isi="$@"
lib=1 #2

if [ "$isi" = "" ]; then
	echo "contoh -->> vclass main.class"
	echo "membuat file java --->> vclass main.class > main.java"
else
	java -jar /usr/bin/vclasslib/lib$lib.jar "$@"
	rm "$@"
fi
